pipeline {
  agent any
    
  tools {nodejs "nodejs"}
    
  stages {
        
    stage('Cloning Git') {
      steps {
        git 'https://github.com/asrilu448/Lvl3.git'
      }
    }
        
    stage('Install dependencies') {
      steps {
        sh 'cd Option1'
        sh 'npm install'
      }
    }
     
    stage('Test') {
      steps {
         sh 'cd Option1'
         sh 'npm test'
      }
    }      
  }
}




